config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"

  resources :users, only: [:new, :create] do 
    resources :discover, only: :index
    resources :movies, only: [:index, :show] do
     resources :parties, only: [:new, :create]
    end
  end

  get "/dashboard", to: "users#show"
  get "/register", to: "users#new"
  get "/login", to: "users#login_form"
  post "/login", to: "users#login_user"
  get "/logout", to: "users#logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/party.rb
class Party < ApplicationRecord
  validates_presence_of :date,
                        :start_time,
                        :duration,
                        :movie_id
  has_many :party_users
  has_many :users, through: :party_users
end

app/models/party_user.rb
class PartyUser < ApplicationRecord
  belongs_to :user
  belongs_to :party
end

app/models/user.rb
class User < ApplicationRecord

  validates_presence_of :name,
                        :email,
                        :password_digest
  has_secure_password

  validates :email, uniqueness: true

  has_many :party_users
  has_many :parties, through: :party_users

  def host?(party)
    user_party = PartyUser.find_by(party: party)
    user_party.user_id == self.id
  end

  def my_parties
		parties.joins(:party_users).where(party_users: {host: true}).distinct
	end

	def party_invites
		parties.joins(:party_users).where(party_users: {host: false}).distinct
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  add_flash_types :error, :success

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private
  def error_message(errors)
    errors.full_messages.join(", ")
  end
end

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController 
  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    if params[:title]
      @movies = MovieFacade.new.get_searched_movies(params[:title])
    else
      @movies = MovieFacade.new.get_top_rated_movies
    end
  end

  def show
    @user = User.find(params[:user_id])
    @movie = MovieFacade.new.get_movie_details(params[:id])
  end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  def new
    if current_user.nil?
      flash[:error] = "You must be logged in or register to continue."
      redirect_to user_movie_path(params[:user_id], params[:movie_id])
    else
      @user = current_user
      @movie = MovieFacade.new.get_movie_details(params[:movie_id])
    
      @users = User.all
    end
  end

    def create
      user = current_user
      @movie = MovieFacade.new.get_movie_details(params[:movie_id])
      new_party = Party.new(party_attributes)
      if new_party.save
        PartyUser.create(user: user, party: new_party, host: user)
        params[:users].each do |user_id|
          next if user_id.empty? || user_id == user.id.to_s
          PartyUser.create!(user: User.find(user_id.to_i), party: new_party, host: false )
        end
        redirect_to dashboard_path
      else
        redirect_to new_user_movie_party_path(user, @movie.movie_id)
        flash[:error] = error_message(new_party.errors)
      end
    end
  private

  def party_attributes
    params.permit(:duration, :start_time, :date, :movie_id, :host_id, :movie_title, :poster_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = user_params  
    user[:email] = user[:email].downcase
    new_user = User.create(user)
    session[:user_id] = new_user.id
    if new_user.save
      redirect_to dashboard_path
    else
      redirect_to register_path
      flash[:error] = error_message(new_user.errors)
    end 
  end

  def show
    if current_user
     @user = current_user
    else
      flash[:error] = "You must be logged in to access your dashboard."
      redirect_to root_path
    end
  end

  def login_form
  end

  def login_user
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.name}"
      redirect_to dashboard_path
    else
      flash[:error] = "Sorry your credentials are bad."
      render :login_form
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private
   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/discover/index.html.erb
<center>
  <%= button_to "Discover Top Rated Movies", user_movies_path(@user), method: :get, local: true, :class =>"btn btn-success" %>
</center>

<br>

<center>
  <%=form_with url: "/users/#{@user.id}/movies", method: :get, local: true do |f|%>
    <%= f.label :title %>
    <%=f.text_field :title %>
    <%=f.submit "Find Movies", :class => "btn btn-secondary" %>
  <% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewingParty</title>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" href="/">Home
            <span class="visually-hidden">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/dashboard">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/register">Register</a>
        </li>
        <li class="nav-item">
        <% if current_user %>
          <a class="nav-link" href="/logout">Log Out</a>
        <% else %>
          <%# <a class="nav-link" href="/login">Log In</a> %>
          <%= button_to "Log In", login_path, local: true %>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "bootswatch-theme", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <% flash.each do |type, message| %>
      <p><%= message %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<center>
  <h1>Movie Results</h1>

  <%= link_to "Discover Page", user_discover_index_path(@user), method: :get, local: true, :class => "text-muted" %>
<br>
<br>
  <% @movies.each do |movie|  %>
    <h5>
      <%= link_to "#{movie.title}", user_movie_path(@user, id: movie.movie_id), method: :get, local: true, :class => "text-secondary" %>
    </h5>
    <p class="text-success">Vote Average: <%= movie.vote_average %></p>
  <% end %>
</center>

app/views/movies/show.html.erb
  <center>
    <%= button_to "Discover Page", user_discover_index_path(@user), method: :get, :class => "btn btn-success" %>
    <%= button_to "Create Viewing Party", new_user_movie_party_path(@user, @movie.movie_id), method: :get, local: true,  :class => "btn btn-secondary" %>
  </center>
<center>

  <h1><%= @movie.title %></h1>
  <h4 class=text-secondary> Summary:</h4> <p><%= @movie.summary %></p>
    <br>
  <h5 class=text-secondary> Runtime:</h5> <%= @movie.runtime %>
    <br>
    <br>
  <h5 class=text-secondary>Vote Average:</h5> <%= @movie.vote_average %></h5>
    <br>
    <br>
  <h5 class=text-secondary>Genres:</h5>
  <% @movie.genres.each do |genre|%>
    <p><%= genre %> </li>
  <% end %>
    <br>
  <h5 class=text-secondary>Cast:</h5>
  <% @movie.cast.each do |cast|%>
    <p class=text-success> <%= "#{cast[:name]}" %></p>  <p class=text-warning> <b class=text-muted>Character:</b> <%= "#{cast[:character]}"%> </p>
  <% end %>

  <h5 class=text-secondary>Reviews:</h5>
  <% @movie.review_info.each do |review|%>
    <p class=text-primary>
      <b><%= "#{review[:author].capitalize} Proclaims:"%><b>
    </p> 
    <p>
      <%= "#{review[:review]}" %>
    </p>
  <% end %>
  <h5 class=text-secondary>Total Reviews:
    <div class=text-success> <%= @movie.total_reviews %> </div>
  </h5>
</center>

app/views/parties/new.html.erb
<h1 class="text-secondary">Create a Viewing Party!!</h1>

<h3>Movie: <%= @movie.title %></h3>
<%= form_with url: user_movie_parties_path(@user, @movie.movie_id), method: :post, local: :true do |f| %>
  <p><%= f.label :duration, "Duration" %></p>
	<p><%= f.number_field :duration, value: @movie.runtime.split(':').map(&:to_i).reduce(0) { |total, t| total * 60 + t } %></p>
	<p><%= f.label :date, "Date" %></p>
	<p><%= f.date_field :date, min: Date.today %></p>
	<p><%= f.label :start_time, "Time" %></p>
	<p><%= f.time_field :start_time %></p>
	<p><%= f.collection_check_boxes :users, @users.reject { |user| user == current_user }, :id, :name %></p>
  <%= f.hidden_field :movie_title, value: @movie.title %>
  <%= f.hidden_field :poster_path, value: @movie.poster_path %>
	<p><%= f.submit "Create Party" %></p>
<% end %>

app/views/users/login_form.html.erb
<%= form_with url: login_path, method: :post do |form| %>
  <%= form.label :email, "Email:"%>
  <%= form.text_field :email %>
  <%= form.label :password, "Password:" %>
  <%= form.text_field :password %>
  <%= form.submit "Login" %>
<% end %>

app/views/users/new.html.erb
 <center>
  <h1 class="text-warning"> Register 
    <small class="text-muted">Become a Party People!</small>
  </h1>
</center>
    
<%= form_with model: @user do |form| %>
  <%= form.label :name, "Name:" %>
  <%= form.text_field :name %>
  <%= form.label :email, "Email:" %>
  <%= form.text_field :email %>
  <%= form.label :password, "Password:" %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation, "Password Confirmation:" %>
  <%= form.password_field :password_confirmation %>
  <%= form.button "Register", class: "btn btn-light" %>
<% end %>

<div style="text-align: center;">
  <p>Already have an account? <%= button_to "Login Here", root_path, method: :get, class: "btn btn-secondary"%></p>
</div>

app/views/users/show.html.erb
<div id="user">
  <h1><%= @user.name %>'s Dashboard</h1>
</div>

<%= button_to "Discover Movies", user_discover_index_path(@user.id),  method: :get, local: true %>

<div id="parties">
  <h2>Viewing Parties: </h2>
  <h3>Parties I'm Hosting:</h3>
    <% @user.my_parties.each do |party| %>
        <p>Movie: <%= party.movie_title%> </p>
        <p>Date: <%= party.date %> </p>
        <p>Start time: <%= party.start_time %> </p>
        <p>Duration: <%= party.duration %> </p>
        <img src=<%= "https://image.tmdb.org/t/p/w200#{party.poster_path}" %>>
        <h3>Attendees:</h4>
        <% party.users.each do |user| %>
          <p><%= user.name unless user.name == @user.name %></p>
        <% end %>
    <% end %>

    <h3>Parties I'm Attending:</h3>
    <% @user.party_invites.each do |party| %>
        <p>Movie: <%= party.movie_title%> </p>
        <p>Date: <%= party.date %> </p>
        <p>Start time: <%= party.start_time %> </p>
        <p>Duration: <%= party.duration %> </p>
        <img src=<%= "https://image.tmdb.org/t/p/w200#{party.poster_path}" %>>
        <% party.users.each do |user| %>
          <% if user == @user%>
            <p><b><%= user.name %></p><b>
          <% else %>
            <p><%= user.name %></p>
          <% end %>
        <% end %>
    <% end %>
</div>

app/views/welcome/index.html.erb
<center><h1 class="text-secondary">Viewing Party</h1></center>



<center><h3 class="text-success">Party People:</h3></center>
<% @users.each do |user| %>
  <center><li> <%= link_to "#{user.name}", dashboard_path, method: :get%> </li></center>
<% end %>
 